---
- name: Install Clickhouse
  hosts:
    - clickhouse
  roles:
    - my_clickhouse

- name: Install Lighthouse
  hosts:
    - Lighthouse
  roles:
    - DEVSYS-15.Lighthouse
  tags:
    - "install Lighthouse"

- name: Install Vector
  hosts:
    - vector
  roles:
    - DEVSYS-15.Vector
  tags:
    - "Install Vector"
    - "Config Vector"
